### ISSUE TITLE
TypeError with publications in Readium 1

### ISSUE THREAD

**Issue by JayPanoz** [edrlab/r2-streamer-js#25]
FYI Readium 1 is failing with all 3 publications on demo server.

[Example url](http://readium-2.surge.sh/?epub=https%3A%2F%2Freadium2.herokuapp.com%2Fpub%2FL2FwcC9taXNjL2VwdWJzL2NoaWxkcmVucy1saXRlcmF0dXJlLmVwdWI%3D%2Fmanifest.json)

Console error:

- TypeError: undefined is not an object (evaluating `'webpubJson.metadata.publisher[0]'`) → `getMetadata` (package_document_parser.js:41)

So that’s

```
// getElemText(metadataElem, "publisher");
metadata.publisher = webpubJson.metadata.publisher[0].name;
```

**Comment by danielweck** [comment]
Thanks Jiminy!
I am closing this issue as this is not a problem with `r2-streamer-js`.

I actually reported about this a little over a year ago :)
https://github.com/readium/readium-js/pull/180#issuecomment-316779856

Problem: there are missing sanity checks in EvidentPoint's prototype implementation (which is a modification of Readium1's parser to convert Readium2's "webpub manifest" format into the internal data structure used by ReadiumJS).

CC @barbender
