### ISSUE TITLE
OPDS JSON Schema validation

### ISSUE THREAD

**Issue by danielweck** [edrlab/r2-streamer-js#32]
@HadrienGardeur this?
https://github.com/opds-community/drafts/tree/master/schema

**Comment by HadrienGardeur** [comment]
Yes that's it

**Comment by danielweck** [comment]
Implemented for the streamer's own OPDS2 feed ( https://github.com/edrlab/r2-streamer-js/commit/70f9f687f3c38d92eb546e885ab42de632e12cc8 ) and for the OPDS v1 to v2 converter ( https://github.com/edrlab/r2-streamer-js/commit/5e1411bee9e1c77432e6cfa295c9a6beb45f0ac5 ).

**Comment by danielweck** [comment]
Demo 1:
https://readium2.now.sh/opds2/publications.json/show

**Comment by danielweck** [comment]
Demo 2 (Feedbooks OPDS feed converted to v2):
https://readium2.now.sh/opds12/https%3A%2F%2Fwww.feedbooks.com%2Fcatalog.atom

**Comment by danielweck** [comment]
Demo 3 (also Feedbooks OPDS v2 conversion, this time "public domain" and "romance"):

https://readium2.now.sh/opds12/http%3A%2F%2F35.234.121.197%2Fpublicdomain%2Fbrowse%2Fen%2Ftop.atom%3Frange%3Dmonth

https://readium2.now.sh/opds12/http%3A%2F%2F35.234.121.197%2Fpublicdomain%2Fbrowse%2Fen%2Ftop.atom%3Fcat%3DFBFIC027000%26range%3Dmonth

**Comment by danielweck** [comment]
Note the PR to contribute JSON Schema changes back to OPDS Community:
https://github.com/opds-community/drafts/pull/2
