### ISSUE TITLE
Can r2-streamer-js generate an OPDS feed?

### ISSUE THREAD

**Issue by rishighan** [edrlab/r2-streamer-js#58]
Like the question says, I have a library of comic books in `cbz` and `cbr` files. What is the most trivial way to generate a feed of these publications for consumption by a downstream app such as [Panels](https://apps.apple.com/us/app/panels-comic-reader/id1236567663) on iOS?

**Comment by danielweck** [comment]
The short answer is "no", this project does not implement a generic OPDS (v1 XML or v2 JSON) feed generator. The streamer does create a basic OPDS2 feed in order to expose the loaded publications, but this is nowhere near as feature-complete as a proper OPDS implementation would be.
