### ISSUE TITLE
Couple of sample mashups do not work

### ISSUE THREAD

**Issue by barbender** [edrlab/r2-streamer-js#6]
Hi Daniel,
A couple of sample mashups are not working due to http/https mismatch:

Reader EPUB.js:
https://s3.amazonaws.com/epubjs-manifest/examples/manifest.html?href=http://localhost:3030/pub/L1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJvbVNoYWtlc3BlYXJlLmVwdWI%3D/manifest.json

- starts working if you change https -> http:
http://s3.amazonaws.com/epubjs-manifest/examples/manifest.html?href=http://localhost:3030/pub/L1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJvbVNoYWtlc3BlYXJlLmVwdWI%3D/manifest.json

Reader HADRIEN BASIC:
https://hadriengardeur.github.io/webpub-manifest/examples/viewer/?manifest=true&href=http%3A%2F%2Flocalhost:3030%2Fpub%2FL1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJvbVNoYWtlc3BlYXJlLmVwdWI%3D%2Fmanifest.json

- does not work even after you change to http:
http://hadriengardeur.github.io/webpub-manifest/examples/viewer/?manifest=true&href=http%3A%2F%2Flocalhost:3030%2Fpub%2FL1VzZXJzL21pY2hhZWxzL3IyLXN0cmVhbWVyLWpzL1RhbGVzRnJvbVNoYWtlc3BlYXJlLmVwdWI%3D%2Fmanifest.json

regards, Michael

**Comment by danielweck** [comment]
Yes, HTTPS cannot reference HTTP content. However the reverse is allowed.

That being said, your links point to `localhost:3030`, so I do not understand how remote domains could possibly access this? Is that just a typo?

**Comment by barbender** [comment]
I guess localhost is accessible by the JS code that is downloaded from http://s3.amazonaws.com/epubjs-manifest/examples/manifest.htm because the code is executed on the local machine.

**Comment by danielweck** [comment]
most HTTP (non-secure) web services / hosts that support secure HTTPS automatically redirect to HTTPS.
that's why the second link doesn't work (github.io)
