### ISSUE TITLE
Is there any way to add information to the metadata when generating the manifest file?

### ISSUE THREAD

**Issue by reconers-taein** [edrlab/r2-streamer-js#73]
I need to migrate old epub files. 

When generating the manifest.json file, I would like to add the 'media-overlay' entry in the code below, please let me know if there is a way to do this.

- as-is

```json
"metadata": {
    "@type": "http://schema.org/Book",
    "title": "Aladdin and the Magic Lamp",
    "identifier": "urn:uuid:978-1-4509-7342-7",
    "author": "retold by Kathryn L. O’Dell",
    "narrator": "Author",
    "publisher": "Benchmark Education Company",
    "language": "en-US",
    "modified": "Tue Apr 07 2015 10:13:00 GMT+0900 (대한민국 표준시)",
    "published": "Tue Feb 10 2015 20:17:22 GMT+0900 (대한민국 표준시)",
    "readingProgression": "ltr",
    "rendition": {
        "layout": "fixed",
        "orientation": "landscape",
        "spread": "auto"
    },
    "rendition:layout": "pre-paginated",
    "rendition:orientation": "landscape",
    "rendition:spread": "auto"
},
```

- to-be

```json
"metadata": {
    "@type": "http://schema.org/Book",
    "title": "Aladdin and the Magic Lamp",
    "identifier": "urn:uuid:978-1-4509-7342-7",
    "author": "retold by Kathryn L. O’Dell",
    "narrator": "Author",
    "publisher": "Benchmark Education Company",
    "language": "en-US",
    "modified": "Tue Apr 07 2015 10:13:00 GMT+0900 (대한민국 표준시)",
    "published": "Tue Feb 10 2015 20:17:22 GMT+0900 (대한민국 표준시)",
    "readingProgression": "ltr",
    "media-overlay": { // < --- need to add this
        "active-class": "-epub-media-overlay-active"
    },
    "rendition": {
        "layout": "fixed",
        "orientation": "landscape",
        "spread": "auto"
    },
    "rendition:layout": "pre-paginated",
    "rendition:orientation": "landscape",
    "rendition:spread": "auto"
    },
```

**Comment by danielweck** [comment]
How to you use this software? Do you compile your own tool with it, or do you use the build-in command line utilities already implemented here? Sorry but I am not sure I understand your use-case. Thank you

**Comment by reconers-taein** [comment]
I'm using server.addPublications to stream epub files from a specific folder. 

I'm assuming that server.addPublications creates a manifest.json file, but am I wrong?

**Comment by reconers-taein** [comment]
> I'm using server.addPublications to stream epub files from a specific folder.
> 
> I'm assuming that server.addPublications creates a manifest.json file, but am I wrong?

**Comment by danielweck** [comment]
The publication object resulting from parsing the original EPUB is created here:

https://github.com/readium/r2-streamer-js/blob/caec233e57fbf7511b9ce21c482541ba956c6a2b/src/http/server.ts#L367

...so you could "patch" the object to inject / force the Media Overlays class.

That being said I am not sure that patching the in-memory Publication object is a good idea, wouldn't it be better to fix the EPUB upstream in the production process? (or alternatively implement a workaround inside the reading system to use a default / different Media Overlays "active" class, if this is what you are trying to achieve.
